{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore }}
  labels:
    {{- include "agi-portal.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.global.region | default "us-west-2" }}
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets
{{- end }}
