apiVersion: v1
kind: ServiceAccount
metadata:
  name: agi-backend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agi-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- if .Values.irsa.enabled }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.irsa.roles.externalSecrets }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agi-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "agi-portal.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
