import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'kk';

export const translations = {
  en: {
    loading: 'Loading...',
    welcome: 'Welcome to Birlik Digital Bank',
    
    dashboard: 'Dashboard',
    transfers: 'Transfers',
    wallet: 'Wallet',
    identity: 'Identity',
    governance: 'Governance',
    profile: 'Profile',
    logout: 'Logout',
    
    login: 'Login',
    register: 'Register',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    createAccount: 'Create Account',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    dontHaveAccount: 'Don\'t have an account?',
    signUp: 'Sign Up',
    loginFailed: 'Login failed. Please check your credentials.',
    signInToAccount: 'Sign in to your account',
    enterUsername: 'Enter your username',
    enterPassword: 'Enter your password',
    optional: 'Optional',
    connect: 'Connect',
    connectWalletOrEnterManually: 'Connect your wallet or enter address manually',
    
    totalTransfers: 'Total Transfers',
    cbdcBalance: 'CBDC Balance',
    fiatBalance: 'Fiat Balance',
    recentTransactions: 'Recent Transactions',
    date: 'Date',
    recipient: 'Recipient',
    amount: 'Amount',
    status: 'Status',
    noTransactionsFound: 'No transactions found.',
    
    crossBorderTransfers: 'Cross-Border Transfers',
    transferFeatures: 'Transfer Features',
    swiftIndependent: 'SWIFT-independent transfers',
    swiftIndependentTransfers: 'SWIFT-independent cross-border transfers',
    multiCurrency: 'Multi-currency support (Fiat, CBDC, Crypto)',
    instantSettlement: 'Instant settlement (3-5 seconds)',
    lowFees: 'Low fees (0.1-0.3%)',
    blockchainVerification: 'Blockchain verification',
    crossBorderSupport: 'Cross-border support for CIS and Asia',
    transactionHistory: 'Transaction History',
    blockchainTx: 'Blockchain TX',
    view: 'View',
    
    multiCurrencyWallet: 'Multi-Currency Wallet',
    walletInformation: 'Wallet Information',
    walletAddress: 'Wallet Address',
    notConnected: 'Not connected',
    ethBalance: 'ETH Balance',
    refreshBalance: 'Refresh Balance',
    noWeb3Wallet: 'No Web3 wallet detected',
    installMetaMask: 'Please install MetaMask or another Web3 wallet to use this feature',
    fiatCbdcBalances: 'Fiat & CBDC Balances',
    walletFeatures: 'Wallet Features',
    
    nftPassport: 'NFT Passport',
    createPassport: 'Create Passport',
    verifyIdentity: 'Verify Identity',
    passportDetails: 'Passport Details',
    passportType: 'Passport Type',
    nationality: 'Nationality',
    dateOfBirth: 'Date of Birth',
    issuedAt: 'Issued At',
    expiresAt: 'Expires At',
    
    daoGovernance: 'DAO Governance',
    activeProposals: 'Active Proposals',
    pastProposals: 'Past Proposals',
    createProposal: 'Create Proposal',
    proposalTitle: 'Proposal Title',
    proposalDescription: 'Proposal Description',
    votingPeriod: 'Voting Period',
    voteFor: 'Vote For',
    voteAgainst: 'Vote Against',
    
    language: 'Language',
    english: 'English',
    russian: 'Russian',
    kazakh: 'Kazakh',
    
    birlikLiveIntegration: 'Birlik Live Integration',
    connectToBirlikLive: 'Connect to Birlik Live',
    birlikLiveFeatures: 'Birlik Live Features',
    birlikFeatures: 'Birlik Digital Bank Features',
    connectedToBirlikLive: 'Connected to Birlik Live',
    connecting: 'Connecting...',
    birlikLiveServices: 'Birlik Live Services',
    maps: 'Maps',
    mapsDescription: 'Interactive maps and location services',
    marketplace: 'Marketplace',
    marketplaceDescription: 'Buy and sell goods and services',
    socialNetwork: 'Social Network',
    socialNetworkDescription: 'Connect with other users',
    
    globalDigitalEconomy: 'Global Digital Economy',
    regionalCenters: 'Regional Centers',
    nationalCenters: 'National Centers',
    digitalFinanceExchange: 'Digital Finance Exchange',
    exchangeRates: 'Exchange Rates',
    globalCitizenID: 'Global Citizen ID',
    hierarchicalStructure: 'Hierarchical Structure',
    globalCenter: 'Global Center',
    asiaRegion: 'Asia Region',
    europeRegion: 'Europe Region',
    americaRegion: 'America Region',
    africaRegion: 'Africa Region',
    australiaOceaniaRegion: 'Australia & Oceania Region',
    blockchainVerified: 'Blockchain Verified',
    globalVerification: 'Global Verification',
    regionalVerification: 'Regional Verification',
    nationalVerification: 'National Verification',
    verificationStatus: 'Verification Status',
    pending: 'Pending',
    verified: 'Verified',
    rejected: 'Rejected',
    createExchange: 'Create Exchange',
    addExchangeRate: 'Add Exchange Rate',
    fromCurrency: 'From Currency',
    toCurrency: 'To Currency',
    rate: 'Rate',
    exchangeType: 'Exchange Type',
    digital: 'Digital',
    real: 'Real',
    supportedCurrencies: 'Supported Currencies',
    noRegionalCentersFound: 'No regional centers found.',
    noNationalCentersFound: 'No national centers found.',
    noExchangesFound: 'No exchanges found.',
    noExchangeRatesFound: 'No exchange rates found.',
    currency: 'Currency',
    languages: 'Languages',
    noPassportFound: 'No passport found.',
    notVerified: 'Not verified',
    noGlobalCitizenID: 'No Global Citizen ID found.',
    createGlobalCitizenID: 'Create Global Citizen ID',
    errorLoadingRegionalCenters: 'Error loading regional centers',
    errorLoadingNationalCenters: 'Error loading national centers',
    selectExchange: 'Select Exchange',
    timestamp: 'Timestamp',
    
    arDashboard: 'AR Dashboard',
    arNotSupported: 'AR Not Supported',
    arWebMockMessage: 'AR view is not supported in web browsers. Showing a mock view instead.',
    arFinancialDashboard: 'AR Financial Dashboard',
    viewBalance: 'View Balance',
    getAIAdvice: 'Get AI Financial Advice',
    aiFinancialAdvice: 'AI Financial Advice',
    adviceError: 'Error loading advice. Please try again.',
    
    avatar3D: '3D Avatar',
    avatar3DLoadError: 'Error loading 3D avatar',
    xpLevel: 'XP Level',
    
    xrViewer: 'XR Viewer',
    xrSupportedDesc: 'Your device supports XR experiences. Start an XR session to explore.',
    startXRSession: 'Start XR Session',
    endXRSession: 'End XR Session',
    xrNotSupported: 'XR is not supported on your device',
    xrBrowserSuggestion: 'Try using Chrome or Edge on a compatible device',
    xrSessionActive: 'XR Session Active',
    
    xpInventory: 'XP Inventory',
    emptyInventory: 'Your inventory is empty. Complete missions to earn items.',
    
    missions: 'Missions',
    noMissionsAvailable: 'No missions available at the moment.',
    startMission: 'Start Mission',
    completed: 'Completed',
    deadline: 'Deadline',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    expert: 'Expert',
    xpReward: 'XP Reward',
    
    smartProgress: 'Smart Progress',
    level: 'Level',
    toNextLevel: 'to next level',
    dailyXP: 'Daily XP',
    weeklyXP: 'Weekly XP',
    monthlyXP: 'Monthly XP',
    novice: 'Novice',
    apprentice: 'Apprentice',
    adept: 'Adept',
    expertRank: 'Expert',
    master: 'Master',
    grandMaster: 'Grand Master',
    
    aiAgent: 'AI Agent',
    collapse: 'Collapse',
    expand: 'Expand',
    askQuestion: 'Ask Question',
    refresh: 'Refresh',
    recentInsights: 'Recent Insights',
    aiInsightExample1: 'Your spending pattern shows potential for 15% savings.',
    aiInsightExample2: 'Consider diversifying your portfolio with CBDC assets.',
    aiInsightExample3: 'Your identity verification is due for renewal next month.',
    
    bonusNFTs: 'Bonus NFTs',
    noNFTsAvailable: 'No NFTs available yet.',
    earnMoreXP: 'Earn more XP to unlock NFTs',
    active: 'Active',
    activate: 'Activate',
    
    zkernelFeed: 'ZKernel Feed',
    zkernelStatus: 'ZKernel Status',
    all: 'All',
    zkernelTransferDesc: 'Completed a secure cross-border transfer',
    zkernelIdentityDesc: 'Identity verification through ZK-proof',
    zkernelGovernanceDesc: 'Participated in DAO governance vote',
    
    devXRMonitor: 'Dev XR Monitor',
    '2DMode': '2D Mode',
    xrMode: 'XR Mode',
    lastUpdated: 'Last Updated',
    cpuUsage: 'CPU Usage',
    memoryUsage: 'Memory Usage',
    networkLatency: 'Network Latency',
    diskUsage: 'Disk Usage',
    activeUsers: 'Active Users',
    xrModeDescription: 'XR mode provides an immersive view of system metrics',
    xrVisualizationPlaceholder: 'XR visualization will appear here',
    
    xpExchange: 'XP Exchange',
    allCategories: 'All Categories',
    digitalRewards: 'Digital Rewards',
    physicalRewards: 'Physical Rewards',
    serviceRewards: 'Service Rewards',
    noRewardsAvailable: 'No rewards available in this category.',
    exchange: 'Exchange',
    remaining: 'Remaining',
    soldOut: 'Sold Out',
    confirmExchange: 'Confirm Exchange',
    exchangeConfirmationText: 'Are you sure you want to exchange {xpCost} XP for {rewardName}?',
    cancel: 'Cancel',
    confirm: 'Confirm',
    xpExchangeNFTDesc: 'Unique digital passport with special privileges',
    xpExchangePremiumDesc: 'Access premium features and services for one month',
    xpExchangeSouvenirDesc: 'Traditional Kazakh handcrafted souvenir shipped to your address',
    
    bank: 'Bank',
    routes: 'Routes',
    dayMode: 'Day Mode',
    nightMode: 'Night Mode',
  },
  ru: {
    loading: 'Загрузка...',
    welcome: 'Добро пожаловать в Birlik Digital Bank',
    
    dashboard: 'Панель управления',
    transfers: 'Переводы',
    wallet: 'Кошелек',
    identity: 'Идентификация',
    governance: 'Управление',
    profile: 'Профиль',
    logout: 'Выйти',
    
    login: 'Вход',
    register: 'Регистрация',
    username: 'Имя пользователя',
    email: 'Электронная почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    fullName: 'Полное имя',
    createAccount: 'Создать аккаунт',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    signIn: 'Войти',
    signingIn: 'Вход...',
    dontHaveAccount: 'Нет аккаунта?',
    signUp: 'Зарегистрироваться',
    loginFailed: 'Ошибка входа. Пожалуйста, проверьте ваши учетные данные.',
    signInToAccount: 'Войдите в свой аккаунт',
    enterUsername: 'Введите имя пользователя',
    enterPassword: 'Введите пароль',
    optional: 'Необязательно',
    connect: 'Подключить',
    connectWalletOrEnterManually: 'Подключите кошелек или введите адрес вручную',
    creatingAccount: 'Создание аккаунта...',
    
    totalTransfers: 'Всего переводов',
    cbdcBalance: 'Баланс CBDC',
    fiatBalance: 'Фиатный баланс',
    recentTransactions: 'Последние транзакции',
    date: 'Дата',
    recipient: 'Получатель',
    amount: 'Сумма',
    status: 'Статус',
    noTransactionsFound: 'Транзакции не найдены.',
    
    crossBorderTransfers: 'Трансграничные переводы',
    transferFeatures: 'Особенности переводов',
    swiftIndependent: 'Переводы без SWIFT',
    swiftIndependentTransfers: 'Трансграничные переводы без SWIFT',
    multiCurrency: 'Поддержка нескольких валют (Фиат, CBDC, Крипто)',
    instantSettlement: 'Мгновенное зачисление (3-5 секунд)',
    lowFees: 'Низкие комиссии (0.1-0.3%)',
    blockchainVerification: 'Верификация через блокчейн',
    crossBorderSupport: 'Поддержка трансграничных переводов для СНГ и Азии',
    transactionHistory: 'История транзакций',
    blockchainTx: 'Блокчейн TX',
    view: 'Просмотр',
    
    multiCurrencyWallet: 'Мультивалютный кошелек',
    walletInformation: 'Информация о кошельке',
    walletAddress: 'Адрес кошелька',
    notConnected: 'Не подключен',
    ethBalance: 'Баланс ETH',
    refreshBalance: 'Обновить баланс',
    noWeb3Wallet: 'Web3 кошелек не обнаружен',
    installMetaMask: 'Пожалуйста, установите MetaMask или другой Web3 кошелек для использования этой функции',
    fiatCbdcBalances: 'Балансы Фиат и CBDC',
    walletFeatures: 'Особенности кошелька',
    
    nftPassport: 'NFT паспорт',
    createPassport: 'Создать паспорт',
    verifyIdentity: 'Подтвердить личность',
    passportDetails: 'Детали паспорта',
    passportType: 'Тип паспорта',
    nationality: 'Гражданство',
    dateOfBirth: 'Дата рождения',
    issuedAt: 'Дата выдачи',
    expiresAt: 'Действителен до',
    
    daoGovernance: 'Управление DAO',
    activeProposals: 'Активные предложения',
    pastProposals: 'Прошлые предложения',
    createProposal: 'Создать предложение',
    proposalTitle: 'Название предложения',
    proposalDescription: 'Описание предложения',
    votingPeriod: 'Период голосования',
    voteFor: 'Голосовать за',
    voteAgainst: 'Голосовать против',
    
    language: 'Язык',
    english: 'Английский',
    russian: 'Русский',
    kazakh: 'Казахский',
    
    birlikLiveIntegration: 'Интеграция с Birlik Live',
    connectToBirlikLive: 'Подключиться к Birlik Live',
    birlikLiveFeatures: 'Функции Birlik Live',
    birlikFeatures: 'Функции Birlik Digital Bank',
    connectedToBirlikLive: 'Подключено к Birlik Live',
    connecting: 'Подключение...',
    birlikLiveServices: 'Сервисы Birlik Live',
    maps: 'Карты',
    mapsDescription: 'Интерактивные карты и сервисы локации',
    marketplace: 'Маркетплейс',
    marketplaceDescription: 'Покупка и продажа товаров и услуг',
    socialNetwork: 'Социальная сеть',
    socialNetworkDescription: 'Общение с другими пользователями',
    
    globalDigitalEconomy: 'Глобальная цифровая экономика',
    regionalCenters: 'Региональные центры',
    nationalCenters: 'Национальные центры',
    digitalFinanceExchange: 'Цифровая финансовая биржа',
    exchangeRates: 'Обменные курсы',
    globalCitizenID: 'Глобальный ID гражданина',
    hierarchicalStructure: 'Иерархическая структура',
    globalCenter: 'Глобальный центр',
    asiaRegion: 'Регион Азия',
    europeRegion: 'Регион Европа',
    americaRegion: 'Регион Америка',
    africaRegion: 'Регион Африка',
    australiaOceaniaRegion: 'Регион Австралия и Океания',
    blockchainVerified: 'Проверено блокчейном',
    globalVerification: 'Глобальная верификация',
    regionalVerification: 'Региональная верификация',
    nationalVerification: 'Национальная верификация',
    verificationStatus: 'Статус верификации',
    pending: 'В ожидании',
    verified: 'Подтверждено',
    rejected: 'Отклонено',
    createExchange: 'Создать биржу',
    addExchangeRate: 'Добавить обменный курс',
    fromCurrency: 'Из валюты',
    toCurrency: 'В валюту',
    rate: 'Курс',
    exchangeType: 'Тип биржи',
    digital: 'Цифровая',
    real: 'Реальная',
    supportedCurrencies: 'Поддерживаемые валюты',
    noRegionalCentersFound: 'Региональные центры не найдены.',
    noNationalCentersFound: 'Национальные центры не найдены.',
    noExchangesFound: 'Биржи не найдены.',
    noExchangeRatesFound: 'Обменные курсы не найдены.',
    currency: 'Валюта',
    languages: 'Языки',
    noPassportFound: 'Паспорт не найден.',
    notVerified: 'Не подтверждено',
    noGlobalCitizenID: 'Глобальный ID гражданина не найден.',
    createGlobalCitizenID: 'Создать Глобальный ID гражданина',
    errorLoadingRegionalCenters: 'Ошибка загрузки региональных центров',
    errorLoadingNationalCenters: 'Ошибка загрузки национальных центров',
    selectExchange: 'Выбрать биржу',
    timestamp: 'Временная метка',
    
    arDashboard: 'AR Панель',
    arNotSupported: 'AR не поддерживается',
    arWebMockMessage: 'AR просмотр не поддерживается в веб-браузерах. Показан макет вместо этого.',
    arFinancialDashboard: 'AR Финансовая панель',
    viewBalance: 'Просмотр баланса',
    getAIAdvice: 'Получить финансовый совет от ИИ',
    aiFinancialAdvice: 'Финансовый совет от ИИ',
    adviceError: 'Ошибка загрузки совета. Пожалуйста, попробуйте снова.',
    
    avatar3D: '3D Аватар',
    avatar3DLoadError: 'Ошибка загрузки 3D аватара',
    xpLevel: 'Уровень XP',
    
    xrViewer: 'XR Просмотрщик',
    xrSupportedDesc: 'Ваше устройство поддерживает XR-опыт. Начните XR-сессию для исследования.',
    startXRSession: 'Начать XR-сессию',
    endXRSession: 'Завершить XR-сессию',
    xrNotSupported: 'XR не поддерживается на вашем устройстве',
    xrBrowserSuggestion: 'Попробуйте использовать Chrome или Edge на совместимом устройстве',
    xrSessionActive: 'XR-сессия активна',
    
    xpInventory: 'XP Инвентарь',
    emptyInventory: 'Ваш инвентарь пуст. Выполняйте миссии, чтобы получать предметы.',
    
    missions: 'Миссии',
    noMissionsAvailable: 'В данный момент нет доступных миссий.',
    startMission: 'Начать миссию',
    completed: 'Завершено',
    deadline: 'Срок',
    easy: 'Легкий',
    medium: 'Средний',
    hard: 'Сложный',
    expert: 'Эксперт',
    xpReward: 'XP Награда',
    
    smartProgress: 'Умный прогресс',
    level: 'Уровень',
    toNextLevel: 'до следующего уровня',
    dailyXP: 'Дневной XP',
    weeklyXP: 'Недельный XP',
    monthlyXP: 'Месячный XP',
    novice: 'Новичок',
    apprentice: 'Ученик',
    adept: 'Адепт',
    expertRank: 'Эксперт',
    master: 'Мастер',
    grandMaster: 'Гранд-мастер',
    
    aiAgent: 'ИИ Агент',
    collapse: 'Свернуть',
    expand: 'Развернуть',
    askQuestion: 'Задать вопрос',
    refresh: 'Обновить',
    recentInsights: 'Недавние выводы',
    aiInsightExample1: 'Ваша модель расходов показывает потенциал для экономии 15%.',
    aiInsightExample2: 'Рассмотрите возможность диверсификации вашего портфеля с активами CBDC.',
    aiInsightExample3: 'Срок действия вашей верификации личности истекает в следующем месяце.',
    
    bonusNFTs: 'Бонусные NFT',
    noNFTsAvailable: 'Пока нет доступных NFT.',
    earnMoreXP: 'Заработайте больше XP, чтобы разблокировать NFT',
    active: 'Активно',
    activate: 'Активировать',
    
    zkernelFeed: 'ZKernel Лента',
    zkernelStatus: 'Статус ZKernel',
    all: 'Все',
    zkernelTransferDesc: 'Завершен безопасный трансграничный перевод',
    zkernelIdentityDesc: 'Верификация личности через ZK-доказательство',
    zkernelGovernanceDesc: 'Участие в голосовании управления DAO',
    
    devXRMonitor: 'Dev XR Монитор',
    '2DMode': '2D Режим',
    xrMode: 'XR Режим',
    lastUpdated: 'Последнее обновление',
    cpuUsage: 'Использование CPU',
    memoryUsage: 'Использование памяти',
    networkLatency: 'Задержка сети',
    diskUsage: 'Использование диска',
    activeUsers: 'Активные пользователи',
    xrModeDescription: 'XR режим предоставляет иммерсивный вид системных метрик',
    xrVisualizationPlaceholder: 'Здесь появится XR визуализация',
    
    xpExchange: 'XP Обмен',
    allCategories: 'Все категории',
    digitalRewards: 'Цифровые награды',
    physicalRewards: 'Физические награды',
    serviceRewards: 'Сервисные награды',
    noRewardsAvailable: 'В этой категории нет доступных наград.',
    exchange: 'Обменять',
    remaining: 'Осталось',
    soldOut: 'Распродано',
    confirmExchange: 'Подтвердить обмен',
    exchangeConfirmationText: 'Вы уверены, что хотите обменять {xpCost} XP на {rewardName}?',
    cancel: 'Отмена',
    confirm: 'Подтвердить',
    xpExchangeNFTDesc: 'Уникальный цифровой паспорт с особыми привилегиями',
    xpExchangePremiumDesc: 'Доступ к премиум-функциям и сервисам на один месяц',
    xpExchangeSouvenirDesc: 'Традиционный казахский сувенир ручной работы, отправленный на ваш адрес',
    
    bank: 'Банк',
    routes: 'Маршруты',
    dayMode: 'Дневной режим',
    nightMode: 'Ночной режим',
  },
  kk: {
    loading: 'Жүктелуде...',
    welcome: 'Birlik Digital Bank-ке қош келдіңіз',
    
    dashboard: 'Басқару тақтасы',
    transfers: 'Аударымдар',
    wallet: 'Әмиян',
    identity: 'Сәйкестендіру',
    governance: 'Басқару',
    profile: 'Профиль',
    logout: 'Шығу',
    
    login: 'Кіру',
    register: 'Тіркелу',
    username: 'Пайдаланушы аты',
    email: 'Электрондық пошта',
    password: 'Құпия сөз',
    confirmPassword: 'Құпия сөзді растаңыз',
    fullName: 'Толық аты-жөні',
    createAccount: 'Тіркелгі жасау',
    creatingAccount: 'Тіркелгі жасалуда...',
    alreadyHaveAccount: 'Тіркелгіңіз бар ма?',
    signIn: 'Кіру',
    signingIn: 'Кіру...',
    dontHaveAccount: 'Тіркелгіңіз жоқ па?',
    signUp: 'Тіркелу',
    loginFailed: 'Кіру қатесі. Тіркелгі деректеріңізді тексеріңіз.',
    signInToAccount: 'Тіркелгіңізге кіріңіз',
    enterUsername: 'Пайдаланушы атын енгізіңіз',
    enterPassword: 'Құпия сөзді енгізіңіз',
    optional: 'Міндетті емес',
    connect: 'Қосылу',
    connectWalletOrEnterManually: 'Әмиянды қосыңыз немесе мекенжайды қолмен енгізіңіз',
    
    totalTransfers: 'Барлық аударымдар',
    cbdcBalance: 'CBDC балансы',
    fiatBalance: 'Фиат балансы',
    recentTransactions: 'Соңғы транзакциялар',
    date: 'Күні',
    recipient: 'Алушы',
    amount: 'Сома',
    status: 'Күйі',
    noTransactionsFound: 'Транзакциялар табылмады.',
    
    crossBorderTransfers: 'Трансшекаралық аударымдар',
    transferFeatures: 'Аударым мүмкіндіктері',
    swiftIndependent: 'SWIFT-тәуелсіз аударымдар',
    swiftIndependentTransfers: 'SWIFT-тәуелсіз трансшекаралық аударымдар',
    multiCurrency: 'Көп валюталы қолдау (Фиат, CBDC, Крипто)',
    instantSettlement: 'Жылдам есеп айырысу (3-5 секунд)',
    lowFees: 'Төмен комиссиялар (0.1-0.3%)',
    blockchainVerification: 'Блокчейн арқылы тексеру',
    crossBorderSupport: 'ТМД және Азия үшін трансшекаралық қолдау',
    transactionHistory: 'Транзакция тарихы',
    blockchainTx: 'Блокчейн TX',
    view: 'Қарау',
    
    multiCurrencyWallet: 'Көп валюталы әмиян',
    walletInformation: 'Әмиян туралы ақпарат',
    walletAddress: 'Әмиян мекенжайы',
    notConnected: 'Қосылмаған',
    ethBalance: 'ETH балансы',
    refreshBalance: 'Балансты жаңарту',
    noWeb3Wallet: 'Web3 әмияны табылмады',
    installMetaMask: 'Бұл мүмкіндікті пайдалану үшін MetaMask немесе басқа Web3 әмиянын орнатыңыз',
    fiatCbdcBalances: 'Фиат және CBDC баланстары',
    walletFeatures: 'Әмиян мүмкіндіктері',
    
    nftPassport: 'NFT паспорты',
    createPassport: 'Паспорт жасау',
    verifyIdentity: 'Жеке басты растау',
    passportDetails: 'Паспорт мәліметтері',
    passportType: 'Паспорт түрі',
    nationality: 'Азаматтығы',
    dateOfBirth: 'Туған күні',
    issuedAt: 'Берілген күні',
    expiresAt: 'Жарамдылық мерзімі',
    
    daoGovernance: 'DAO басқару',
    activeProposals: 'Белсенді ұсыныстар',
    pastProposals: 'Өткен ұсыныстар',
    createProposal: 'Ұсыныс жасау',
    proposalTitle: 'Ұсыныс атауы',
    proposalDescription: 'Ұсыныс сипаттамасы',
    votingPeriod: 'Дауыс беру кезеңі',
    voteFor: 'Қолдау',
    voteAgainst: 'Қарсы дауыс',
    
    language: 'Тіл',
    english: 'Ағылшын',
    russian: 'Орыс',
    kazakh: 'Қазақ',
    
    birlikLiveIntegration: 'Birlik Live интеграциясы',
    connectToBirlikLive: 'Birlik Live-ке қосылу',
    birlikLiveFeatures: 'Birlik Live мүмкіндіктері',
    birlikFeatures: 'Birlik Digital Bank мүмкіндіктері',
    connectedToBirlikLive: 'Birlik Live-ке қосылды',
    connecting: 'Қосылуда...',
    birlikLiveServices: 'Birlik Live қызметтері',
    maps: 'Карталар',
    mapsDescription: 'Интерактивті карталар және орналасу қызметтері',
    marketplace: 'Маркетплейс',
    marketplaceDescription: 'Тауарлар мен қызметтерді сатып алу және сату',
    socialNetwork: 'Әлеуметтік желі',
    socialNetworkDescription: 'Басқа пайдаланушылармен байланыс',
    
    globalDigitalEconomy: 'Жаһандық цифрлық экономика',
    regionalCenters: 'Аймақтық орталықтар',
    nationalCenters: 'Ұлттық орталықтар',
    digitalFinanceExchange: 'Цифрлық қаржы биржасы',
    exchangeRates: 'Айырбас бағамдары',
    globalCitizenID: 'Жаһандық азаматтық ID',
    hierarchicalStructure: 'Иерархиялық құрылым',
    globalCenter: 'Жаһандық орталық',
    asiaRegion: 'Азия аймағы',
    europeRegion: 'Еуропа аймағы',
    americaRegion: 'Америка аймағы',
    africaRegion: 'Африка аймағы',
    australiaOceaniaRegion: 'Австралия және Океания аймағы',
    blockchainVerified: 'Блокчейнмен расталған',
    globalVerification: 'Жаһандық растау',
    regionalVerification: 'Аймақтық растау',
    nationalVerification: 'Ұлттық растау',
    verificationStatus: 'Растау күйі',
    pending: 'Күтілуде',
    verified: 'Расталған',
    rejected: 'Қабылданбаған',
    createExchange: 'Биржа құру',
    addExchangeRate: 'Айырбас бағамын қосу',
    fromCurrency: 'Бастапқы валюта',
    toCurrency: 'Мақсатты валюта',
    rate: 'Бағам',
    exchangeType: 'Биржа түрі',
    digital: 'Цифрлық',
    real: 'Нақты',
    supportedCurrencies: 'Қолдау көрсетілетін валюталар',
    noRegionalCentersFound: 'Аймақтық орталықтар табылмады.',
    noNationalCentersFound: 'Ұлттық орталықтар табылмады.',
    noExchangesFound: 'Биржалар табылмады.',
    noExchangeRatesFound: 'Айырбастау бағамдары табылмады.',
    currency: 'Валюта',
    languages: 'Тілдер',
    noPassportFound: 'Паспорт табылмады.',
    notVerified: 'Тексерілмеген',
    noGlobalCitizenID: 'Жаһандық азаматтық ID табылмады.',
    createGlobalCitizenID: 'Жаһандық азаматтық ID жасау',
    errorLoadingRegionalCenters: 'Аймақтық орталықтарды жүктеу қатесі',
    errorLoadingNationalCenters: 'Ұлттық орталықтарды жүктеу қатесі',
    selectExchange: 'Биржаны таңдаңыз',
    timestamp: 'Уақыт белгісі',
    
    arDashboard: 'AR Тақтасы',
    arNotSupported: 'AR қолданылмайды',
    arWebMockMessage: 'AR көрінісі веб-браузерлерде қолданылмайды. Оның орнына макет көрсетілген.',
    arFinancialDashboard: 'AR Қаржылық тақта',
    viewBalance: 'Балансты көру',
    getAIAdvice: 'ЖИ қаржылық кеңесін алу',
    aiFinancialAdvice: 'ЖИ қаржылық кеңесі',
    adviceError: 'Кеңес жүктеу қатесі. Қайталап көріңіз.',
    
    avatar3D: '3D Аватар',
    avatar3DLoadError: '3D аватарды жүктеу қатесі',
    xpLevel: 'XP Деңгейі',
    
    xrViewer: 'XR Көрсеткіш',
    xrSupportedDesc: 'Сіздің құрылғыңыз XR тәжірибесін қолдайды. Зерттеу үшін XR сеансын бастаңыз.',
    startXRSession: 'XR сеансын бастау',
    endXRSession: 'XR сеансын аяқтау',
    xrNotSupported: 'XR сіздің құрылғыңызда қолданылмайды',
    xrBrowserSuggestion: 'Үйлесімді құрылғыда Chrome немесе Edge пайдаланып көріңіз',
    xrSessionActive: 'XR сеансы белсенді',
    
    xpInventory: 'XP Қоймасы',
    emptyInventory: 'Сіздің қоймаңыз бос. Заттар алу үшін миссияларды орындаңыз.',
    
    missions: 'Миссиялар',
    noMissionsAvailable: 'Қазіргі уақытта қол жетімді миссиялар жоқ.',
    startMission: 'Миссияны бастау',
    completed: 'Аяқталды',
    deadline: 'Мерзімі',
    easy: 'Оңай',
    medium: 'Орташа',
    hard: 'Қиын',
    expert: 'Сарапшы',
    xpReward: 'XP Сыйақы',
    
    smartProgress: 'Ақылды прогресс',
    level: 'Деңгей',
    toNextLevel: 'келесі деңгейге дейін',
    dailyXP: 'Күнделікті XP',
    weeklyXP: 'Апталық XP',
    monthlyXP: 'Айлық XP',
    novice: 'Жаңадан бастаушы',
    apprentice: 'Шәкірт',
    adept: 'Шебер',
    expertRank: 'Сарапшы',
    master: 'Мастер',
    grandMaster: 'Ұлы мастер',
    
    aiAgent: 'ЖИ Агент',
    collapse: 'Жию',
    expand: 'Кеңейту',
    askQuestion: 'Сұрақ қою',
    refresh: 'Жаңарту',
    recentInsights: 'Соңғы түсініктер',
    aiInsightExample1: 'Сіздің шығын үлгіңіз 15% үнемдеу әлеуетін көрсетеді.',
    aiInsightExample2: 'CBDC активтерімен портфеліңізді әртараптандыруды қарастырыңыз.',
    aiInsightExample3: 'Сіздің жеке басыңызды растау мерзімі келесі айда аяқталады.',
    
    bonusNFTs: 'Бонустық NFT',
    noNFTsAvailable: 'Әзірге қол жетімді NFT жоқ.',
    earnMoreXP: 'NFT-ларды ашу үшін көбірек XP табыңыз',
    active: 'Белсенді',
    activate: 'Белсендіру',
    
    zkernelFeed: 'ZKernel Лентасы',
    zkernelStatus: 'ZKernel Күйі',
    all: 'Барлығы',
    zkernelTransferDesc: 'Қауіпсіз трансшекаралық аударым аяқталды',
    zkernelIdentityDesc: 'ZK-дәлелдеме арқылы жеке басты растау',
    zkernelGovernanceDesc: 'DAO басқару дауыс беруіне қатысу',
    
    devXRMonitor: 'Dev XR Мониторы',
    '2DMode': '2D Режим',
    xrMode: 'XR Режим',
    lastUpdated: 'Соңғы жаңарту',
    cpuUsage: 'CPU қолданысы',
    memoryUsage: 'Жад қолданысы',
    networkLatency: 'Желі кідірісі',
    diskUsage: 'Диск қолданысы',
    activeUsers: 'Белсенді пайдаланушылар',
    xrModeDescription: 'XR режимі жүйелік метрикалардың иммерсивті көрінісін ұсынады',
    xrVisualizationPlaceholder: 'XR визуализациясы осы жерде пайда болады',
    
    xpExchange: 'XP Айырбастау',
    allCategories: 'Барлық санаттар',
    digitalRewards: 'Цифрлық сыйақылар',
    physicalRewards: 'Физикалық сыйақылар',
    serviceRewards: 'Қызмет сыйақылары',
    noRewardsAvailable: 'Бұл санатта қол жетімді сыйақылар жоқ.',
    exchange: 'Айырбастау',
    remaining: 'Қалған',
    soldOut: 'Сатылып кетті',
    confirmExchange: 'Айырбастауды растау',
    exchangeConfirmationText: 'Сіз {xpCost} XP-ті {rewardName} үшін айырбастағыңыз келетініне сенімдісіз бе?',
    cancel: 'Болдырмау',
    confirm: 'Растау',
    xpExchangeNFTDesc: 'Арнайы артықшылықтары бар бірегей цифрлық паспорт',
    xpExchangePremiumDesc: 'Бір ай бойы премиум функциялар мен қызметтерге қол жеткізу',
    xpExchangeSouvenirDesc: 'Сіздің мекенжайыңызға жіберілетін дәстүрлі қазақ қолөнер сувенирі',
    
    bank: 'Банк',
    routes: 'Бағыттар',
    dayMode: 'Күндізгі режим',
    nightMode: 'Түнгі режим'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const storedLanguage = localStorage.getItem('language') as Language;
  const [language, setLanguage] = useState<Language>(storedLanguage || 'kk');

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: keyof typeof translations.en): string => {
    return (translations[language] && translations[language][key]) || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
