import React, { createContext, useState, useContext, ReactNode } from 'react';

export type Language = 'en' | 'ru' | 'kk';

export const translations = {
  en: {
    loading: 'Loading...',
    welcome: 'Welcome to Birlik Digital Bank',
    
    dashboard: 'Dashboard',
    transfers: 'Transfers',
    wallet: 'Wallet',
    identity: 'Identity',
    governance: 'Governance',
    profile: 'Profile',
    logout: 'Logout',
    
    login: 'Login',
    register: 'Register',
    username: 'Username',
    email: 'Email',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    fullName: 'Full Name',
    createAccount: 'Create Account',
    creatingAccount: 'Creating account...',
    alreadyHaveAccount: 'Already have an account?',
    signIn: 'Sign In',
    signingIn: 'Signing in...',
    dontHaveAccount: 'Don\'t have an account?',
    signUp: 'Sign Up',
    loginFailed: 'Login failed. Please check your credentials.',
    sessionExpired: 'Session Expired',
    sessionExpiredMessage: 'Your session has expired. Please log in again to continue.',
    loginAgain: 'Login Again',
    cancel: 'Cancel',
    signInToAccount: 'Sign in to your account',
    enterUsername: 'Enter your username',
    enterPassword: 'Enter your password',
    optional: 'Optional',
    connect: 'Connect',
    connectWalletOrEnterManually: 'Connect your wallet or enter address manually',
    
    totalTransfers: 'Total Transfers',
    cbdcBalance: 'CBDC Balance',
    fiatBalance: 'Fiat Balance',
    recentTransactions: 'Recent Transactions',
    date: 'Date',
    recipient: 'Recipient',
    amount: 'Amount',
    status: 'Status',
    noTransactionsFound: 'No transactions found.',
    
    crossBorderTransfers: 'Cross-Border Transfers',
    transferFeatures: 'Transfer Features',
    swiftIndependent: 'SWIFT-independent transfers',
    swiftIndependentTransfers: 'SWIFT-independent cross-border transfers',
    multiCurrency: 'Multi-currency support (Fiat, CBDC, Crypto)',
    instantSettlement: 'Instant settlement (3-5 seconds)',
    lowFees: 'Low fees (0.1-0.3%)',
    blockchainVerification: 'Blockchain verification',
    crossBorderSupport: 'Cross-border support for CIS and Asia',
    transactionHistory: 'Transaction History',
    blockchainTx: 'Blockchain TX',
    view: 'View',
    
    multiCurrencyWallet: 'Multi-Currency Wallet',
    walletInformation: 'Wallet Information',
    walletAddress: 'Wallet Address',
    notConnected: 'Not connected',
    ethBalance: 'ETH Balance',
    refreshBalance: 'Refresh Balance',
    noWeb3Wallet: 'No Web3 wallet detected',
    installMetaMask: 'Please install MetaMask or another Web3 wallet to use this feature',
    fiatCbdcBalances: 'Fiat & CBDC Balances',
    walletFeatures: 'Wallet Features',
    
    nftPassport: 'NFT Passport',
    createPassport: 'Create Passport',
    verifyIdentity: 'Verify Identity',
    passportDetails: 'Passport Details',
    passportType: 'Passport Type',
    nationality: 'Nationality',
    dateOfBirth: 'Date of Birth',
    issuedAt: 'Issued At',
    expiresAt: 'Expires At',
    
    daoGovernance: 'DAO Governance',
    activeProposals: 'Active Proposals',
    pastProposals: 'Past Proposals',
    createProposal: 'Create Proposal',
    proposalTitle: 'Proposal Title',
    proposalDescription: 'Proposal Description',
    votingPeriod: 'Voting Period',
    voteFor: 'Vote For',
    voteAgainst: 'Vote Against',
    
    language: 'Language',
    english: 'English',
    russian: 'Russian',
    kazakh: 'Kazakh',
    
    birlikLiveIntegration: 'Birlik Live Integration',
    connectToBirlikLive: 'Connect to Birlik Live',
    birlikLiveFeatures: 'Birlik Live Features',
    birlikFeatures: 'Birlik Digital Bank Features',
    connectedToBirlikLive: 'Connected to Birlik Live',
    connecting: 'Connecting...',
    birlikLiveServices: 'Birlik Live Services',
    maps: 'Maps',
    mapsDescription: 'Interactive maps and location services',
    marketplace: 'Marketplace',
    marketplaceDescription: 'Buy and sell goods and services',
    socialNetwork: 'Social Network',
    socialNetworkDescription: 'Connect with other users',
    
    globalDigitalEconomy: 'Global Digital Economy',
    regionalCenters: 'Regional Centers',
    nationalCenters: 'National Centers',
    digitalFinanceExchange: 'Digital Finance Exchange',
    exchangeRates: 'Exchange Rates',
    globalCitizenID: 'Global Citizen ID',
    hierarchicalStructure: 'Hierarchical Structure',
    globalCenter: 'Global Center',
    asiaRegion: 'Asia Region',
    europeRegion: 'Europe Region',
    americaRegion: 'America Region',
    africaRegion: 'Africa Region',
    australiaOceaniaRegion: 'Australia & Oceania Region',
    blockchainVerified: 'Blockchain Verified',
    globalVerification: 'Global Verification',
    regionalVerification: 'Regional Verification',
    nationalVerification: 'National Verification',
    verificationStatus: 'Verification Status',
    pending: 'Pending',
    verified: 'Verified',
    rejected: 'Rejected',
    createExchange: 'Create Exchange',
    addExchangeRate: 'Add Exchange Rate',
    fromCurrency: 'From Currency',
    toCurrency: 'To Currency',
    rate: 'Rate',
    exchangeType: 'Exchange Type',
    digital: 'Digital',
    real: 'Real',
    supportedCurrencies: 'Supported Currencies',
    noRegionalCentersFound: 'No regional centers found.',
    noNationalCentersFound: 'No national centers found.',
    noExchangesFound: 'No exchanges found.',
    noExchangeRatesFound: 'No exchange rates found.',
    currency: 'Currency',
    languages: 'Languages',
    noPassportFound: 'No passport found.',
    notVerified: 'Not verified',
    noGlobalCitizenID: 'No Global Citizen ID found.',
    createGlobalCitizenID: 'Create Global Citizen ID',
    errorLoadingRegionalCenters: 'Error loading regional centers',
    errorLoadingNationalCenters: 'Error loading national centers',
    selectExchange: 'Select Exchange',
    timestamp: 'Timestamp',
    
    arDashboard: 'AR Dashboard',
    arNotSupported: 'AR Not Supported',
    arWebMockMessage: 'AR view is not supported in web browsers. Showing a mock view instead.',
    arFinancialDashboard: 'AR Financial Dashboard',
    viewBalance: 'View Balance',
    getAIAdvice: 'Get AI Financial Advice',
    aiFinancialAdvice: 'AI Financial Advice',
    adviceError: 'Error loading advice. Please try again.',
  },
  ru: {
    loading: 'Загрузка...',
    welcome: 'Добро пожаловать в Birlik Digital Bank',
    
    dashboard: 'Панель управления',
    transfers: 'Переводы',
    wallet: 'Кошелек',
    identity: 'Идентификация',
    governance: 'Управление',
    profile: 'Профиль',
    logout: 'Выйти',
    
    login: 'Вход',
    register: 'Регистрация',
    username: 'Имя пользователя',
    email: 'Электронная почта',
    password: 'Пароль',
    confirmPassword: 'Подтвердите пароль',
    fullName: 'Полное имя',
    createAccount: 'Создать аккаунт',
    alreadyHaveAccount: 'Уже есть аккаунт?',
    signIn: 'Войти',
    signingIn: 'Вход...',
    dontHaveAccount: 'Нет аккаунта?',
    signUp: 'Зарегистрироваться',
    loginFailed: 'Ошибка входа. Пожалуйста, проверьте ваши учетные данные.',
    sessionExpired: 'Сессия истекла',
    sessionExpiredMessage: 'Ваша сессия истекла. Пожалуйста, войдите снова для продолжения.',
    loginAgain: 'Войти снова',
    cancel: 'Отмена',
    signInToAccount: 'Войдите в свой аккаунт',
    enterUsername: 'Введите имя пользователя',
    enterPassword: 'Введите пароль',
    optional: 'Необязательно',
    connect: 'Подключить',
    connectWalletOrEnterManually: 'Подключите кошелек или введите адрес вручную',
    creatingAccount: 'Создание аккаунта...',
    
    totalTransfers: 'Всего переводов',
    cbdcBalance: 'Баланс CBDC',
    fiatBalance: 'Фиатный баланс',
    recentTransactions: 'Последние транзакции',
    date: 'Дата',
    recipient: 'Получатель',
    amount: 'Сумма',
    status: 'Статус',
    noTransactionsFound: 'Транзакции не найдены.',
    
    crossBorderTransfers: 'Трансграничные переводы',
    transferFeatures: 'Особенности переводов',
    swiftIndependent: 'Переводы без SWIFT',
    swiftIndependentTransfers: 'Трансграничные переводы без SWIFT',
    multiCurrency: 'Поддержка нескольких валют (Фиат, CBDC, Крипто)',
    instantSettlement: 'Мгновенное зачисление (3-5 секунд)',
    lowFees: 'Низкие комиссии (0.1-0.3%)',
    blockchainVerification: 'Верификация через блокчейн',
    crossBorderSupport: 'Поддержка трансграничных переводов для СНГ и Азии',
    transactionHistory: 'История транзакций',
    blockchainTx: 'Блокчейн TX',
    view: 'Просмотр',
    
    multiCurrencyWallet: 'Мультивалютный кошелек',
    walletInformation: 'Информация о кошельке',
    walletAddress: 'Адрес кошелька',
    notConnected: 'Не подключен',
    ethBalance: 'Баланс ETH',
    refreshBalance: 'Обновить баланс',
    noWeb3Wallet: 'Web3 кошелек не обнаружен',
    installMetaMask: 'Пожалуйста, установите MetaMask или другой Web3 кошелек для использования этой функции',
    fiatCbdcBalances: 'Балансы Фиат и CBDC',
    walletFeatures: 'Особенности кошелька',
    
    nftPassport: 'NFT паспорт',
    createPassport: 'Создать паспорт',
    verifyIdentity: 'Подтвердить личность',
    passportDetails: 'Детали паспорта',
    passportType: 'Тип паспорта',
    nationality: 'Гражданство',
    dateOfBirth: 'Дата рождения',
    issuedAt: 'Дата выдачи',
    expiresAt: 'Действителен до',
    
    daoGovernance: 'Управление DAO',
    activeProposals: 'Активные предложения',
    pastProposals: 'Прошлые предложения',
    createProposal: 'Создать предложение',
    proposalTitle: 'Название предложения',
    proposalDescription: 'Описание предложения',
    votingPeriod: 'Период голосования',
    voteFor: 'Голосовать за',
    voteAgainst: 'Голосовать против',
    
    language: 'Язык',
    english: 'Английский',
    russian: 'Русский',
    kazakh: 'Казахский',
    
    birlikLiveIntegration: 'Интеграция с Birlik Live',
    connectToBirlikLive: 'Подключиться к Birlik Live',
    birlikLiveFeatures: 'Функции Birlik Live',
    birlikFeatures: 'Функции Birlik Digital Bank',
    connectedToBirlikLive: 'Подключено к Birlik Live',
    connecting: 'Подключение...',
    birlikLiveServices: 'Сервисы Birlik Live',
    maps: 'Карты',
    mapsDescription: 'Интерактивные карты и сервисы локации',
    marketplace: 'Маркетплейс',
    marketplaceDescription: 'Покупка и продажа товаров и услуг',
    socialNetwork: 'Социальная сеть',
    socialNetworkDescription: 'Общение с другими пользователями',
    
    globalDigitalEconomy: 'Глобальная цифровая экономика',
    regionalCenters: 'Региональные центры',
    nationalCenters: 'Национальные центры',
    digitalFinanceExchange: 'Цифровая финансовая биржа',
    exchangeRates: 'Обменные курсы',
    globalCitizenID: 'Глобальный ID гражданина',
    hierarchicalStructure: 'Иерархическая структура',
    globalCenter: 'Глобальный центр',
    asiaRegion: 'Регион Азия',
    europeRegion: 'Регион Европа',
    americaRegion: 'Регион Америка',
    africaRegion: 'Регион Африка',
    australiaOceaniaRegion: 'Регион Австралия и Океания',
    blockchainVerified: 'Проверено блокчейном',
    globalVerification: 'Глобальная верификация',
    regionalVerification: 'Региональная верификация',
    nationalVerification: 'Национальная верификация',
    verificationStatus: 'Статус верификации',
    pending: 'В ожидании',
    verified: 'Подтверждено',
    rejected: 'Отклонено',
    createExchange: 'Создать биржу',
    addExchangeRate: 'Добавить обменный курс',
    fromCurrency: 'Из валюты',
    toCurrency: 'В валюту',
    rate: 'Курс',
    exchangeType: 'Тип биржи',
    digital: 'Цифровая',
    real: 'Реальная',
    supportedCurrencies: 'Поддерживаемые валюты',
    noRegionalCentersFound: 'Региональные центры не найдены.',
    noNationalCentersFound: 'Национальные центры не найдены.',
    noExchangesFound: 'Биржи не найдены.',
    noExchangeRatesFound: 'Обменные курсы не найдены.',
    currency: 'Валюта',
    languages: 'Языки',
    noPassportFound: 'Паспорт не найден.',
    notVerified: 'Не подтверждено',
    noGlobalCitizenID: 'Глобальный ID гражданина не найден.',
    createGlobalCitizenID: 'Создать Глобальный ID гражданина',
    errorLoadingRegionalCenters: 'Ошибка загрузки региональных центров',
    errorLoadingNationalCenters: 'Ошибка загрузки национальных центров',
    selectExchange: 'Выбрать биржу',
    timestamp: 'Временная метка',
    
    arDashboard: 'AR Панель',
    arNotSupported: 'AR не поддерживается',
    arWebMockMessage: 'AR просмотр не поддерживается в веб-браузерах. Показан макет вместо этого.',
    arFinancialDashboard: 'AR Финансовая панель',
    viewBalance: 'Просмотр баланса',
    getAIAdvice: 'Получить финансовый совет от ИИ',
    aiFinancialAdvice: 'Финансовый совет от ИИ',
    adviceError: 'Ошибка загрузки совета. Пожалуйста, попробуйте снова.',
  },
  kk: {
    loading: 'Жүктелуде...',
    welcome: 'Birlik Digital Bank-ке қош келдіңіз',
    
    dashboard: 'Басқару тақтасы',
    transfers: 'Аударымдар',
    wallet: 'Әмиян',
    identity: 'Сәйкестендіру',
    governance: 'Басқару',
    profile: 'Профиль',
    logout: 'Шығу',
    
    login: 'Кіру',
    register: 'Тіркелу',
    username: 'Пайдаланушы аты',
    email: 'Электрондық пошта',
    password: 'Құпия сөз',
    confirmPassword: 'Құпия сөзді растаңыз',
    fullName: 'Толық аты-жөні',
    createAccount: 'Тіркелгі жасау',
    creatingAccount: 'Тіркелгі жасалуда...',
    alreadyHaveAccount: 'Тіркелгіңіз бар ма?',
    signIn: 'Кіру',
    signingIn: 'Кіру...',
    dontHaveAccount: 'Тіркелгіңіз жоқ па?',
    signUp: 'Тіркелу',
    loginFailed: 'Кіру қатесі. Тіркелгі деректеріңізді тексеріңіз.',
    sessionExpired: 'Сессия аяқталды',
    sessionExpiredMessage: 'Сіздің сессияңыз аяқталды. Жалғастыру үшін қайта кіріңіз.',
    loginAgain: 'Қайта кіру',
    cancel: 'Болдырмау',
    signInToAccount: 'Тіркелгіңізге кіріңіз',
    enterUsername: 'Пайдаланушы атын енгізіңіз',
    enterPassword: 'Құпия сөзді енгізіңіз',
    optional: 'Міндетті емес',
    connect: 'Қосылу',
    connectWalletOrEnterManually: 'Әмиянды қосыңыз немесе мекенжайды қолмен енгізіңіз',
    
    totalTransfers: 'Барлық аударымдар',
    cbdcBalance: 'CBDC балансы',
    fiatBalance: 'Фиат балансы',
    recentTransactions: 'Соңғы транзакциялар',
    date: 'Күні',
    recipient: 'Алушы',
    amount: 'Сома',
    status: 'Күйі',
    noTransactionsFound: 'Транзакциялар табылмады.',
    
    crossBorderTransfers: 'Трансшекаралық аударымдар',
    transferFeatures: 'Аударым мүмкіндіктері',
    swiftIndependent: 'SWIFT-тәуелсіз аударымдар',
    swiftIndependentTransfers: 'SWIFT-тәуелсіз трансшекаралық аударымдар',
    multiCurrency: 'Көп валюталы қолдау (Фиат, CBDC, Крипто)',
    instantSettlement: 'Жылдам есеп айырысу (3-5 секунд)',
    lowFees: 'Төмен комиссиялар (0.1-0.3%)',
    blockchainVerification: 'Блокчейн арқылы тексеру',
    crossBorderSupport: 'ТМД және Азия үшін трансшекаралық қолдау',
    transactionHistory: 'Транзакция тарихы',
    blockchainTx: 'Блокчейн TX',
    view: 'Қарау',
    
    multiCurrencyWallet: 'Көп валюталы әмиян',
    walletInformation: 'Әмиян туралы ақпарат',
    walletAddress: 'Әмиян мекенжайы',
    notConnected: 'Қосылмаған',
    ethBalance: 'ETH балансы',
    refreshBalance: 'Балансты жаңарту',
    noWeb3Wallet: 'Web3 әмияны табылмады',
    installMetaMask: 'Бұл мүмкіндікті пайдалану үшін MetaMask немесе басқа Web3 әмиянын орнатыңыз',
    fiatCbdcBalances: 'Фиат және CBDC баланстары',
    walletFeatures: 'Әмиян мүмкіндіктері',
    
    nftPassport: 'NFT паспорты',
    createPassport: 'Паспорт жасау',
    verifyIdentity: 'Жеке басты растау',
    passportDetails: 'Паспорт мәліметтері',
    passportType: 'Паспорт түрі',
    nationality: 'Азаматтығы',
    dateOfBirth: 'Туған күні',
    issuedAt: 'Берілген күні',
    expiresAt: 'Жарамдылық мерзімі',
    
    daoGovernance: 'DAO басқару',
    activeProposals: 'Белсенді ұсыныстар',
    pastProposals: 'Өткен ұсыныстар',
    createProposal: 'Ұсыныс жасау',
    proposalTitle: 'Ұсыныс атауы',
    proposalDescription: 'Ұсыныс сипаттамасы',
    votingPeriod: 'Дауыс беру кезеңі',
    voteFor: 'Қолдау',
    voteAgainst: 'Қарсы дауыс',
    
    language: 'Тіл',
    english: 'Ағылшын',
    russian: 'Орыс',
    kazakh: 'Қазақ',
    
    birlikLiveIntegration: 'Birlik Live интеграциясы',
    connectToBirlikLive: 'Birlik Live-ке қосылу',
    birlikLiveFeatures: 'Birlik Live мүмкіндіктері',
    birlikFeatures: 'Birlik Digital Bank мүмкіндіктері',
    connectedToBirlikLive: 'Birlik Live-ке қосылды',
    connecting: 'Қосылуда...',
    birlikLiveServices: 'Birlik Live қызметтері',
    maps: 'Карталар',
    mapsDescription: 'Интерактивті карталар және орналасу қызметтері',
    marketplace: 'Маркетплейс',
    marketplaceDescription: 'Тауарлар мен қызметтерді сатып алу және сату',
    socialNetwork: 'Әлеуметтік желі',
    socialNetworkDescription: 'Басқа пайдаланушылармен байланыс',
    
    globalDigitalEconomy: 'Жаһандық цифрлық экономика',
    regionalCenters: 'Аймақтық орталықтар',
    nationalCenters: 'Ұлттық орталықтар',
    digitalFinanceExchange: 'Цифрлық қаржы биржасы',
    exchangeRates: 'Айырбас бағамдары',
    globalCitizenID: 'Жаһандық азаматтық ID',
    hierarchicalStructure: 'Иерархиялық құрылым',
    globalCenter: 'Жаһандық орталық',
    asiaRegion: 'Азия аймағы',
    europeRegion: 'Еуропа аймағы',
    americaRegion: 'Америка аймағы',
    africaRegion: 'Африка аймағы',
    australiaOceaniaRegion: 'Австралия және Океания аймағы',
    blockchainVerified: 'Блокчейнмен расталған',
    globalVerification: 'Жаһандық растау',
    regionalVerification: 'Аймақтық растау',
    nationalVerification: 'Ұлттық растау',
    verificationStatus: 'Растау күйі',
    pending: 'Күтілуде',
    verified: 'Расталған',
    rejected: 'Қабылданбаған',
    createExchange: 'Биржа құру',
    addExchangeRate: 'Айырбас бағамын қосу',
    fromCurrency: 'Бастапқы валюта',
    toCurrency: 'Мақсатты валюта',
    rate: 'Бағам',
    exchangeType: 'Биржа түрі',
    digital: 'Цифрлық',
    real: 'Нақты',
    supportedCurrencies: 'Қолдау көрсетілетін валюталар',
    noRegionalCentersFound: 'Аймақтық орталықтар табылмады.',
    noNationalCentersFound: 'Ұлттық орталықтар табылмады.',
    noExchangesFound: 'Биржалар табылмады.',
    noExchangeRatesFound: 'Айырбастау бағамдары табылмады.',
    currency: 'Валюта',
    languages: 'Тілдер',
    noPassportFound: 'Паспорт табылмады.',
    notVerified: 'Тексерілмеген',
    noGlobalCitizenID: 'Жаһандық азаматтық ID табылмады.',
    createGlobalCitizenID: 'Жаһандық азаматтық ID жасау',
    errorLoadingRegionalCenters: 'Аймақтық орталықтарды жүктеу қатесі',
    errorLoadingNationalCenters: 'Ұлттық орталықтарды жүктеу қатесі',
    selectExchange: 'Биржаны таңдаңыз',
    timestamp: 'Уақыт белгісі',
    
    arDashboard: 'AR Тақтасы',
    arNotSupported: 'AR қолданылмайды',
    arWebMockMessage: 'AR көрінісі веб-браузерлерде қолданылмайды. Оның орнына макет көрсетілген.',
    arFinancialDashboard: 'AR Қаржылық тақта',
    viewBalance: 'Балансты көру',
    getAIAdvice: 'ЖИ қаржылық кеңесін алу',
    aiFinancialAdvice: 'ЖИ қаржылық кеңесі',
    adviceError: 'Кеңес жүктеу қатесі. Қайталап көріңіз.'
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const storedLanguage = localStorage.getItem('language') as Language;
  const [language, setLanguage] = useState<Language>(storedLanguage || 'kk');

  const handleSetLanguage = (newLanguage: Language) => {
    setLanguage(newLanguage);
    localStorage.setItem('language', newLanguage);
  };

  const t = (key: keyof typeof translations.en): string => {
    return (translations[language] && translations[language][key]) || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
