"""Add global citizen ID and other new columns

Revision ID: 7031464dea0d
Revises: 
Create Date: 2025-05-21 13:45:42.211455

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7031464dea0d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.drop_index('ix_currencies_code', table_name='currencies')
        op.drop_index('ix_currencies_id', table_name='currencies')
        op.drop_table('currencies')
    except Exception:
        pass
        
    try:
        op.drop_index('ix_transactions_id', table_name='transactions')
        op.drop_index('ix_transactions_recipient', table_name='transactions')
        op.drop_index('ix_transactions_sender', table_name='transactions')
        op.drop_table('transactions')
    except Exception:
        pass
        
    for column_name, column_type in [
        ('blockchain_verified', sa.Boolean()),
        ('global_status', sa.String()),
        ('regional_status', sa.String()),
        ('national_status', sa.String())
    ]:
        try:
            op.add_column('nft_passports', sa.Column(column_name, column_type, nullable=True))
        except Exception:
            pass  # Column might already exist
    
    for column_name, column_type in [
        ('global_citizen_id', sa.String()),
        ('national_center_id', sa.Integer()),
        ('preferred_language', sa.String())
    ]:
        try:
            op.add_column('users', sa.Column(column_name, column_type, nullable=True))
        except Exception:
            pass  # Column might already exist
    
    with op.batch_alter_table('users') as batch_op:
        batch_op.create_unique_constraint('uq_users_global_citizen_id', ['global_citizen_id'])
        batch_op.create_foreign_key('fk_users_national_center_id', 'national_centers', 
                                   ['national_center_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'preferred_language')
    op.drop_column('users', 'national_center_id')
    op.drop_column('users', 'global_citizen_id')
    op.drop_column('nft_passports', 'national_status')
    op.drop_column('nft_passports', 'regional_status')
    op.drop_column('nft_passports', 'global_status')
    op.drop_column('nft_passports', 'blockchain_verified')
    op.create_table('transactions',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sender', sa.VARCHAR(), nullable=True),
    sa.Column('recipient', sa.VARCHAR(), nullable=True),
    sa.Column('amount', sa.FLOAT(), nullable=True),
    sa.Column('currency', sa.VARCHAR(), nullable=True),
    sa.Column('blockchain_tx_hash', sa.VARCHAR(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('fee', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_transactions_sender', 'transactions', ['sender'], unique=False)
    op.create_index('ix_transactions_recipient', 'transactions', ['recipient'], unique=False)
    op.create_index('ix_transactions_id', 'transactions', ['id'], unique=False)
    op.create_table('currencies',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('code', sa.VARCHAR(), nullable=True),
    sa.Column('name', sa.VARCHAR(), nullable=True),
    sa.Column('is_cbdc', sa.BOOLEAN(), nullable=True),
    sa.Column('is_crypto', sa.BOOLEAN(), nullable=True),
    sa.Column('is_fiat', sa.BOOLEAN(), nullable=True),
    sa.Column('blockchain_address', sa.VARCHAR(), nullable=True),
    sa.Column('exchange_rate_to_tenge', sa.FLOAT(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_currencies_id', 'currencies', ['id'], unique=False)
    op.create_index('ix_currencies_code', 'currencies', ['code'], unique=1)
    # ### end Alembic commands ###
